### ISSUE TITLE
PixelmonEconomyBridge is not compatible with 1.20.1 (just works on 1.20.2)

### ISSUE THREAD

**Issue by Scorezyy** [EverNife/PixelmonEconomyBridge#2]
Error:
`

[03:04:20] [Server thread/WARN] []: java.lang.IllegalArgumentException: Cannot find br.com.finalcraft.pixelmoneconomybridge.compat.v1_20_R1.reforged.factory.PixelmonEconomyFactoryImpl
[03:04:20] [Server thread/WARN] []: 	at br.com.finalcraft.evernifecore.util.FCReflectionUtil.getClass(FCReflectionUtil.java:469)
[03:04:20] [Server thread/WARN] []: 	at br.com.finalcraft.evernifecore.util.FCReflectionUtil.getConstructor(FCReflectionUtil.java:403)
[03:04:20] [Server thread/WARN] []: 	at br.com.finalcraft.pixelmoneconomybridge.common.factory.PixelmonEconomyFactory.create(PixelmonEconomyFactory.java:16)
[03:04:20] [Server thread/WARN] []: 	at br.com.finalcraft.pixelmoneconomybridge.PixelmonEconomyBridge$1.run(PixelmonEconomyBridge.java:60)
[03:04:20] [Server thread/WARN] []: 	at TRANSFORMER/forge@47.3.5/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78)
[03:04:20] [Server thread/WARN] []: 	at TRANSFORMER/forge@47.3.5/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:416)
[03:04:20] [Server thread/WARN] []: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1132)
[03:04:20] [Server thread/WARN] []: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:360)
[03:04:20] [Server thread/WARN] []: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1070)
[03:04:20] [Server thread/WARN] []: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:909)
[03:04:20] [Server thread/WARN] []: 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285)
[03:04:20] [Server thread/WARN] []: 	at java.base/java.lang.Thread.run(Thread.java:840)
[03:04:20] [Server thread/WARN] []: Caused by: java.lang.ClassNotFoundException: br.com.finalcraft.pixelmoneconomybridge.compat.v1_20_R1.reforged.factory.PixelmonEconomyFactoryImpl
[03:04:20] [Server thread/WARN] []: 	at TRANSFORMER/forge@47.3.5/org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:186)
[03:04:20] [Server thread/WARN] []: 	at TRANSFORMER/forge@47.3.5/org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:138)
[03:04:20] [Server thread/WARN] []: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[03:04:20] [Server thread/WARN] []: 	at java.base/java.lang.Class.forName0(Native Method)
[03:04:20] [Server thread/WARN] []: 	at java.base/java.lang.Class.forName(Class.java:467)
[03:04:20] [Server thread/WARN] []: 	at TRANSFORMER/forge@47.3.5/com.mohistmc.bukkit.remapping.ReflectionHandler_25.redirectClassForName(ReflectionHandler.java:233)
[03:04:20] [Server thread/WARN] []: 	at TRANSFORMER/forge@47.3.5/com.mohistmc.bukkit.remapping.ReflectionHandler_25.redirectClassForName(ReflectionHandler.java:220)
[03:04:20] [Server thread/WARN] []: 	at br.com.finalcraft.evernifecore.util.FCReflectionUtil.getClass(FCReflectionUtil.java:467)
[03:04:20] [Server thread/WARN] []: 	... 11 more`

**Comment by EverNife** [comment]
It seems you are running on 1.20.1

I though pixelmon only worked on 1.20.2

What is the pixelmon's version you are using?

Also, are you able to join the server with the pixelmon mod?
